---
  - name: Install Dependencies
    apt:
      name:
        - apt-transport-https
        - software-properties-common
        - wget
      state: latest

  - name: Add Grafana APT Repository Key
    apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present

  - name: Add Grafana APT Repository
    apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      state: present

  - name: Install Grafana
    apt:
      name: grafana
      state: present

  - name: Start and Enable Grafana Service
    systemd:
      name: grafana-server
      enabled: yes
      state: started

  - name: Adding Influxdb in the repository
    shell: |
      wget -q https://repos.influxdata.com/influxdb.key
      sleep 5
      echo '23a1c8836f0afc5ed24e0486339d7cc8f6790b83886c4c96995b88a061c5bb5d influxdb.key' | sha256sum -c && cat influxdb.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdb.gpg > /dev/null
      sleep 5
      echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdb.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list

  - name: Installing Influxdb
    apt:
      name:
        - influxdb

  - name: Making sure that the Influxdb is enabled and started
    service:
      name: influxdb
      state: started
      enabled: true

  - name: Install Prerequisites on Ubuntu
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - apt-transport-https
      - software-properties-common
    when: ansible_distribution == "Ubuntu"

  - name: Install Prometheus on Ubuntu
    apt:
      name: prometheus
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Update Prometheus on Ubuntu
    apt:
      name: prometheus
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Start/Restart Prometheus
    service:
      name: prometheus
      state: restarted
      enabled: true
